### ISSUE TITLE
Unable to access docs

### ISSUE THREAD

**Issue by OverLordGoldDragon** [HunterMcGushion/hyperparameter_hunter#177]
Every page shows

![image](https://user-images.githubusercontent.com/16495490/62657218-f831e180-b933-11e9-9400-d337c578ef26.png)

Any remedy?

**Comment by HunterMcGushion** [comment]
Thanks for bringing this up! I can't seem to reproduce the problem locally. I was able to pull up "https://hyperparameter-hunter.readthedocs.io/en/latest/quick_start.html" without issue
![Screen Shot 2019-08-07 at 2 33 44 PM](https://user-images.githubusercontent.com/11300915/62659630-bea3ab00-b920-11e9-8dd7-7bab3c410d1c.png)
*Side note: I just noticed two typos on the Environment section of this page, which I'm fixing now. Just add `()` after `data = load_breast_cancer` and change the value of `shuffle` in `cv_params=dict(n_splits=5, shuffle=2, random_state=32)` to True/False*

Can you please try going to "https://hyperparameter-hunter.readthedocs.io/en/stable/quick_start.html", instead? Just change the "latest" part to "stable". 

Since I can't reproduce the issue, I'm not really sure what's going on, but would you mind trying to visit the [HH docs homepage](https://hyperparameter-hunter.readthedocs.io/en/stable/index.html), and then trying to visit some other non-HyperparameterHunter ReadTheDocs pages? What browser are you using?

**Comment by OverLordGoldDragon** [comment]
@HunterMcGushion  Everything works now, it appeared to be a temporary issue. Thank you for the response.
